version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1
    restart: always
    volumes:
      - ${REPO}/docker-volumes/postgres-data:/var/lib/postgresql/data
      - ./postgresql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=ndxpro123!
      - TZ=${TZ}
    ports:
      - 55432:5432

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    volumes:
      - ${REPO}/docker-volumes/mongodb-data:/data/db
      - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=ndxpro123!
      - TZ=${TZ}
    ports:
      - 57017:27017

  redis:
    container_name: redis
    image: redis:6.2
    restart: always
    command: redis-server --requirepass ndxpro123!
    volumes:
      - ${REPO}/docker-volumes/redis-data/data:/data
      - ${REPO}/docker-volumes/redis-data/redis.conf:/usr/local/etc/redis/redis.conf
      - ${REPO}/docker-volumes/redis-data/users.acl:/etc/redis/users.acl
    environment:
      - TZ=${TZ}
    ports:
      - 56379:6379
      
networks:
  default:
    name: ndxpro
    external: true
