server:
  port: 8081
spring:
  application:
    name: DATASERVICE-SERVICE

  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

databroker:
#  url: "http://172.16.28.217:54006"
  url: "http://172.16.28.222:54011"
  api-path: "/ndxpro/v1/broker/entities"

logging:
  logstash:
    url: localhost:50000

# API 목록을 알파벳순으로 정렬
springdoc:
  swagger-ui:
    tagsSorter: alpha