version: '3.8'

services:
  union-twin-fe:
    image: 172.16.28.217:12000/union-twin-fe:latest
    restart: always
    environment:
      - NDXPRO_ENV_TOKEN=${REACT_APP_TOKEN}
      - NDXPRO_ENV_API_URL=${REACT_APP_API_URL}
      - NDXPRO_ENV_API_OUTSIDE_URL=${REACT_APP_API_OUTSIDE_URL}
      - NDXPRO_ENV_DIGITAL_TWIN_SEARCH_URL=${REACT_APP_DIGITAL_TWIN_SEARCH_URL}
      - NDXPRO_ENV_VIEWER_URL=${REACT_APP_VIEWER_URL}
      - NDXPRO_ENV_PREDICTOR_TOOL_URL=${REACT_APP_PREDICTOR_TOOL_URL}
      - NDXPRO_ENV_DISCRETE_SIMULATOR_URL=${REACT_APP_DISCRETE_SIMULATOR_URL}
      - NDXPRO_ENV_SERVICE_LOGIC_TOOL_URL=${REACT_APP_SERVICE_LOGIC_TOOL_URL}
      - NDXPRO_ENV_DIGITAL_TWIN_METADATA_REGISTRATION=${REACT_APP_DIGITAL_TWIN_METADATA_REGISTRATION}
      - NDXPRO_ENV_METADATA_VISUALIZATION_GRAPH=${REACT_APP_METADATA_VISUALIZATION_GRAPH}
      - NDXPRO_ENV_UNION_OBJECT_SYNC_ENGINE_MANAGEMENT=${REACT_APP_UNION_OBJECT_SYNC_ENGINE_MANAGEMENT}
      - NDXPRO_ENV_VERIFICATION_DATA_ADDITION_MANAGEMENT=${REACT_APP_VERIFICATION_DATA_ADDITION_MANAGEMENT}
    ports:
      - '50031:80'
