spring:
  sleuth:
    sampler:
      probability: 1.0 # 기본값 0.1  샘플링 정의 0~1(100%)
  zipkin:
    base-url: http://172.16.28.7:9411/ # zipkin 주소
  config:
    activate:
      on-profile: local
  application:
    name: DATAMANAGER-SERVICE
  data:
    mongodb:
      host: 13.209.73.228
      port: 27017
      authentication-database: admin
      database: ndxpro
      username: ndxpro
      password: ndxpro123!


logging:
  logstash:
    url: 172.16.28.7:50000
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

#elastic:
#  apm:
#    application_packages: kr.co.e8ight.ndxpro_v1_datamanager
#    server_urls: http://172.16.28.41:9200
#    service_name: my-application


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#
