package kr.co.e8ight.ndxpro_v1_datamanager.util;

public class ResponseMessage {

    public final static String DATA_MODEL_CREATE_SUCCESS = "DATA MODEL CREATE SUCCESS";
    public final static String DATA_MODEL_UPDATE_SUCCESS = "DATA MODEL UPDATE SUCCESS";
    public final static String DATA_MODEL_DELETE_SUCCESS = "DATA MODEL DELETE SUCCESS";
    public final static String DATA_MODEL_VERSION_UP_SUCCESS = "DATA MODEL VERSION UP SUCCESS";

    public final static String DATA_MODEL_USING_UPDATE_SUCCESS = "DATA MODEL USING UPDATE SUCCESS";
    public final static String DATA_MODEL_READY_UPDATE_SUCCESS = "DATA MODEL READY UPDATE SUCCESS";






    public final static String CONTEXT_CREATE_SUCCESS = "CONTEXT CREATE SUCCESS";
    public final static String CONTEXT_UPDATE_SUCCESS = "CONTEXT UPDATE SUCCESS";
    public final static String CONTEXT_DELETE_SUCCESS = "CONTEXT DELETE SUCCESS";


    public final static String ATTRIBUTE_SCHEMA_CREATE_SUCCESS = "ATTRIBUTE SCHEMA CREATE SUCCESS";

    public final static String ATTRIBUTE_SCHEMA_DELETE_SUCCESS = "ATTRIBUTE SCHEMA DELETE SUCCESS";

    public final static String ATTRIBUTE_SCHEMA_UPDATE_SUCCESS = "ATTRIBUTE SCHEMA UPDATE SUCCESS";

    public final static String ATTRIBUTE_SCHEMA_REGISTER_SUCCESS = "속성 스키마 등록 성공";

    public final static String ATTRIBUTE_CREATE_SUCCESS = "ATTRIBUTE CREATE SUCCESS";
    public final static String ATTRIBUTE_DELETE_SUCCESS = "ATTRIBUTE DELETE SUCCESS";
    public final static String ATTRIBUTE_UPDATE_SUCCESS = "ATTRIBUTE UPDATE SUCCESS";
    public final static String ATTRIBUTE_REGISTER_SUCCESS = "ATTRIBUTE REGISTER SUCCESS";

    public final static String ATTRIBUTE_REGISTER_CANCELLATION_SUCCESS = "ATTRIBUTE REGISTER CANCELLATION SUCCESS";



}
