//package kr.co.e8ight.ndxpro_v1_datamanager.defaultvalue;
//
//public class DataModelDefasultValue {
//
//
//    public static final String dataModel = "\n"
//            + "    {\n"
//            + "    \"id\": \"urn:ngsi-ld:Vehicle:\",\n"
//            + "    \"version\": \"0.0.1\",\n"
//            + "    \"type\": \"Vehicle\",\n"
//            + "    \"typeUri\": \"https://uri.e8ight/ngsi-ld/Vehicle\",\n"
//            + "    \"title\": \"NDX-PRO - Vehicle DataModel\",\n"
//            + "    \"description\": \"Information on a given Vehicle\",\n"
//            + "    \"attributeNames\": [\n"
//            + "        {\n"
//            + "        \"vehicleType\": \"https://e8.co.kr/data-models#vehicleType\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"speed\": \"https://e8.co.kr/data-models#speed\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"linkTo\": \"https://e8.co.kr/data-models#linkTo\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"location\": \"location\"\n"
//            + "        }\n"
//            + "    ],\n"
//            + "    \"attributes\": {\n"
//            + "        \"test\": {\n"
//            + "            \"type\": \"Property\",\n"
//            + "            \"valueType\" : \"ArrayObject\",\n"
//            + "            \"objectMember\": [\n"
//            + "                {\n"
//            + "                \"size\": {\n"
//            + "                    \"valueType\": \"Integer\"\n"
//            + "                },\n"
//            + "                \"grade\": {\n"
//            + "                    \"valueType\": \"String\"\n"
//            + "                }\n"
//            + "                },\n"
//            + "                {\n"
//            + "                \"width\": {\n"
//            + "                   \"valueType\": \"Double\"\n"
//            + "                    }\n"
//            + "                }\n"
//            + "            ]\n"
//            + "        },\n"
//            + "        \"linkTo\": {\n"
//            + "        \"type\": \"Relationship\",\n"
//            + "        \"description\": \"링크 정보\",\n"
//            + "        \"valueType\": \"String\",\n"
//            + "        \"modelType\": [\n"
//            + "            \"e8.co.kr/data-models#Link\"\n"
//            + "        ]\n"
//            + "        },\n"
//            + "\n"
//            + "        \"location\": {\n"
//            + "        \"type\": \"GeoProperty\",\n"
//            + "        \"description\": \"차량 위치\",\n"
//            + "        \"valueType\": \"POINT\",\n"
//            + "        \"childAttributes\": {\n"
//            + "            \"observedAt\": {\n"
//            + "            \"valueType\": \"DateTime\"\n"
//            + "            }\n"
//            + "        }\n"
//            + "        },\n"
//            + "        \"vehicleType\": {\n"
//            + "        \"type\": \"Property\",\n"
//            + "        \"description\": \"차량 종류\",\n"
//            + "        \"valueType\": \"Enum\",\n"
//            + "        \"valid\": {\n"
//            + "            \"minLength\": 1,\n"
//            + "            \"maxLength\": 256\n"
//            + "        },\n"
//            + "        \"enum\": [\n"
//            + "            \"bus\",\n"
//            + "            \"truck\",\n"
//            + "            \"bike\",\n"
//            + "            \"sedan\"\n"
//            + "        ]\n"
//            + "        },\n"
//            + "        \"speed\": {\n"
//            + "        \"type\": \"Property\",\n"
//            + "        \"description\": \"차량 속도\",\n"
//            + "        \"valueType\": \"Double\",\n"
//            + "        \"valid\": {\n"
//            + "            \"minimum\": 0\n"
//            + "        },\n"
//            + "        \"childAttributes\": {\n"
//            + "            \"unitCode\": {\n"
//            + "            \"valueType\": \"Enum\",\n"
//            + "            \"enum\": [\n"
//            + "                \"km/h\",\n"
//            + "                \"mph\"\n"
//            + "            ]\n"
//            + "            },\n"
//            + "            \"observedAt\": {\n"
//            + "            \"valueType\": \"DateTime\"\n"
//            + "            }\n"
//            + "        }\n"
//            + "        }\n"
//            + "    },\n"
//            + "    \"required\": [\n"
//            + "        \"speed\",\n"
//            + "        \"location\"\n"
//            + "    ],\n"
//            + "    \"reference\": [\n"
//            + "        \"https://geojson.org/schema/Geometry.json\"\n"
//            + "    ],\n"
//            + "    \"@context\": \"http://172.16.28.35:3005/e8ight-context.jsonld\"\n"
//            + "    }";
//
//
//    public static final String secondDataModel = "\n"
//            + "    {\n"
//            + "    \"id\": \"urn:ngsi-ld:Test:\",\n"
//            + "    \"version\": \"0.0.1\",\n"
//            + "    \"type\": \"Test\",\n"
//            + "    \"typeUri\": \"https://uri.e8ight/ngsi-ld/Test\",\n"
//            + "    \"title\": \"NDX-PRO - Vehicle DataModel\",\n"
//            + "    \"description\": \"Information on a given Vehicle\",\n"
//            + "    \"attributeNames\": [\n"
//            + "        {\n"
//            + "        \"vehicleType\": \"https://e8.co.kr/data-models#vehicleType\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"speed\": \"https://e8.co.kr/data-models#speed\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"linkTo\": \"https://e8.co.kr/data-models#linkTo\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"location\": \"location\"\n"
//            + "        }\n"
//            + "    ],\n"
//            + "    \"attributes\": {\n"
//            + "        \"test\": {\n"
//            + "            \"type\": \"Property\",\n"
//            + "            \"valueType\" : \"ArrayObject\",\n"
//            + "            \"objectMember\": [\n"
//            + "                {\n"
//            + "                \"size\": {\n"
//            + "                    \"valueType\": \"Integer\"\n"
//            + "                },\n"
//            + "                \"grade\": {\n"
//            + "                    \"valueType\": \"String\"\n"
//            + "                }\n"
//            + "                },\n"
//            + "                {\n"
//            + "                \"width\": {\n"
//            + "                   \"valueType\": \"Double\"\n"
//            + "                    }\n"
//            + "                }\n"
//            + "            ]\n"
//            + "        },\n"
//            + "        \"linkTo\": {\n"
//            + "        \"type\": \"Relationship\",\n"
//            + "        \"description\": \"링크 정보\",\n"
//            + "        \"valueType\": \"String\",\n"
//            + "        \"modelType\": [\n"
//            + "            \"e8.co.kr/data-models#Link\"\n"
//            + "        ]\n"
//            + "        },\n"
//            + "\n"
//            + "        \"location\": {\n"
//            + "        \"type\": \"GeoProperty\",\n"
//            + "        \"description\": \"차량 위치\",\n"
//            + "        \"valueType\": \"POINT\",\n"
//            + "        \"childAttributes\": {\n"
//            + "            \"observedAt\": {\n"
//            + "            \"valueType\": \"DateTime\"\n"
//            + "            }\n"
//            + "        }\n"
//            + "        },\n"
//            + "        \"vehicleType\": {\n"
//            + "        \"type\": \"Property\",\n"
//            + "        \"description\": \"차량 종류\",\n"
//            + "        \"valueType\": \"Enum\",\n"
//            + "        \"valid\": {\n"
//            + "            \"minLength\": 1,\n"
//            + "            \"maxLength\": 256\n"
//            + "        },\n"
//            + "        \"enum\": [\n"
//            + "            \"bus\",\n"
//            + "            \"truck\",\n"
//            + "            \"bike\",\n"
//            + "            \"sedan\"\n"
//            + "        ]\n"
//            + "        },\n"
//            + "        \"speed\": {\n"
//            + "        \"type\": \"Property\",\n"
//            + "        \"description\": \"차량 속도\",\n"
//            + "        \"valueType\": \"Double\",\n"
//            + "        \"valid\": {\n"
//            + "            \"minimum\": 0\n"
//            + "        },\n"
//            + "        \"childAttributes\": {\n"
//            + "            \"unitCode\": {\n"
//            + "            \"valueType\": \"Enum\",\n"
//            + "            \"enum\": [\n"
//            + "                \"km/h\",\n"
//            + "                \"mph\"\n"
//            + "            ]\n"
//            + "            },\n"
//            + "            \"observedAt\": {\n"
//            + "            \"valueType\": \"DateTime\"\n"
//            + "            }\n"
//            + "        }\n"
//            + "        }\n"
//            + "    },\n"
//            + "    \"required\": [\n"
//            + "        \"speed\",\n"
//            + "        \"location\"\n"
//            + "    ],\n"
//            + "    \"reference\": [\n"
//            + "        \"https://geojson.org/schema/Geometry.json\"\n"
//            + "    ],\n"
//            + "    \"@context\": \"http://172.16.28.35:3005/e8ight-context.jsonld\"\n"
//            + "    }";
//
//    public static final String WrongAttribute = "{\n"
//            + "  \"attributes\": {\n"
//            + "    \"location\": {\n"
//            + "      \"type\": \"WrongProperty\",\n"
//            + "      \"description\": \"신호운영정보 위치\",\n"
//            + "      \"valueType\": \"POINT\"\n"
//            + "    },\n"
//            + "    \"signalType\": {\n"
//            + "      \"type\": \"Property\",\n"
//            + "      \"description\": \"신호 종류\",\n"
//            + "      \"valueType\": \"Enum\"\n"
//            + "    }\n"
//            + "  }\n"
//            + "}";
//
//
//    public static final String updateDataModel = "\n"
//
//            + "    {\n"
//            + "    \"id\": \"urn:ngsi-ld:Vehicle:\",\n"
//            + "    \"version\": \"0.0.2\",\n"
//            + "    \"type\": \"Vehicle\",\n"
//            + "    \"typeUri\": \"https://uri.e8ight/ngsi-ld/Vehicle\",\n"
//            + "    \"title\": \"test\",\n"
//            + "    \"description\": \"Information on a given Vehicle\",\n"
//            + "    \"attributeNames\": [\n"
//            + "        {\n"
//            + "        \"vehicleType\": \"https://e8.co.kr/data-models#vehicleType\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"speed\": \"https://e8.co.kr/data-models#speed\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"linkTo\": \"https://e8.co.kr/data-models#linkTo\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"location\": \"location\"\n"
//            + "        }\n"
//            + "    ],\n"
//            + "    \"attributes\": {\n"
//            + "        \"test\": {\n"
//            + "            \"type\": \"Property\",\n"
//            + "            \"valueType\" : \"ArrayObject\",\n"
//            + "            \"objectMember\": [\n"
//            + "                {\n"
//            + "                \"size\": {\n"
//            + "                    \"valueType\": \"Integer\"\n"
//            + "                },\n"
//            + "                \"grade\": {\n"
//            + "                    \"valueType\": \"String\"\n"
//            + "                }\n"
//            + "                },\n"
//            + "                {\n"
//            + "                \"width\": {\n"
//            + "                   \"valueType\": \"Double\"\n"
//            + "                    }\n"
//            + "                }\n"
//            + "            ]\n"
//            + "        },\n"
//            + "        \"linkTo\": {\n"
//            + "        \"type\": \"Relationship\",\n"
//            + "        \"description\": \"링크 정보\",\n"
//            + "        \"valueType\": \"String\",\n"
//            + "        \"modelType\": [\n"
//            + "            \"e8.co.kr/data-models#Link\"\n"
//            + "        ]\n"
//            + "        },\n"
//            + "\n"
//            + "        \"location\": {\n"
//            + "        \"type\": \"GeoProperty\",\n"
//            + "        \"description\": \"차량 위치\",\n"
//            + "        \"valueType\": \"POINT\",\n"
//            + "        \"childAttributes\": {\n"
//            + "            \"observedAt\": {\n"
//            + "            \"valueType\": \"DateTime\"\n"
//            + "            }\n"
//            + "        }\n"
//            + "        },\n"
//            + "        \"vehicleType\": {\n"
//            + "        \"type\": \"Property\",\n"
//            + "        \"description\": \"차량 종류\",\n"
//            + "        \"valueType\": \"Enum\",\n"
//            + "        \"valid\": {\n"
//            + "            \"minLength\": 1,\n"
//            + "            \"maxLength\": 256\n"
//            + "        },\n"
//            + "        \"enum\": [\n"
//            + "            \"bus\",\n"
//            + "            \"truck\",\n"
//            + "            \"bike\",\n"
//            + "            \"sedan\"\n"
//            + "        ]\n"
//            + "        },\n"
//            + "        \"speed\": {\n"
//            + "        \"type\": \"Property\",\n"
//            + "        \"description\": \"차량 속도\",\n"
//            + "        \"valueType\": \"Double\",\n"
//            + "        \"valid\": {\n"
//            + "            \"minimum\": 0\n"
//            + "        },\n"
//            + "        \"childAttributes\": {\n"
//            + "            \"unitCode\": {\n"
//            + "            \"valueType\": \"Enum\",\n"
//            + "            \"enum\": [\n"
//            + "                \"km/h\",\n"
//            + "                \"mph\"\n"
//            + "            ]\n"
//            + "            },\n"
//            + "            \"observedAt\": {\n"
//            + "            \"valueType\": \"DateTime\"\n"
//            + "            }\n"
//            + "        }\n"
//            + "        }\n"
//            + "    },\n"
//            + "    \"required\": [\n"
//            + "        \"speed\",\n"
//            + "        \"location\"\n"
//            + "    ],\n"
//            + "    \"reference\": [\n"
//            + "        \"https://geojson.org/schema/Geometry.json\"\n"
//            + "    ],\n"
//            + "    \"@context\": \"http://172.16.28.35:3005/e8ight-context.jsonld\"\n"
//            + "    }";
//
//
//    public static final String wrongTypeUpdateDataModel = "\n"
//
//            + "    {\n"
//            + "    \"id\": \"urn:ngsi-ld:Test:\",\n"
//            + "    \"version\": \"0.0.2\",\n"
//            + "    \"type\": \"Test\",\n"
//            + "    \"typeUri\": \"https://uri.e8ight/ngsi-ld/Test\",\n"
//            + "    \"title\": \"test\",\n"
//            + "    \"description\": \"Information on a given Vehicle\",\n"
//            + "    \"attributeNames\": [\n"
//            + "        {\n"
//            + "        \"vehicleType\": \"https://e8.co.kr/data-models#vehicleType\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"speed\": \"https://e8.co.kr/data-models#speed\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"linkTo\": \"https://e8.co.kr/data-models#linkTo\"\n"
//            + "        },\n"
//            + "        {\n"
//            + "        \"location\": \"location\"\n"
//            + "        }\n"
//            + "    ],\n"
//            + "    \"attributes\": {\n"
//            + "        \"test\": {\n"
//            + "            \"type\": \"Property\",\n"
//            + "            \"valueType\" : \"ArrayObject\",\n"
//            + "            \"objectMember\": [\n"
//            + "                {\n"
//            + "                \"size\": {\n"
//            + "                    \"valueType\": \"Integer\"\n"
//            + "                },\n"
//            + "                \"grade\": {\n"
//            + "                    \"valueType\": \"String\"\n"
//            + "                }\n"
//            + "                },\n"
//            + "                {\n"
//            + "                \"width\": {\n"
//            + "                   \"valueType\": \"Double\"\n"
//            + "                    }\n"
//            + "                }\n"
//            + "            ]\n"
//            + "        },\n"
//            + "        \"linkTo\": {\n"
//            + "        \"type\": \"Relationship\",\n"
//            + "        \"description\": \"링크 정보\",\n"
//            + "        \"valueType\": \"String\",\n"
//            + "        \"modelType\": [\n"
//            + "            \"e8.co.kr/data-models#Link\"\n"
//            + "        ]\n"
//            + "        },\n"
//            + "\n"
//            + "        \"location\": {\n"
//            + "        \"type\": \"GeoProperty\",\n"
//            + "        \"description\": \"차량 위치\",\n"
//            + "        \"valueType\": \"POINT\",\n"
//            + "        \"childAttributes\": {\n"
//            + "            \"observedAt\": {\n"
//            + "            \"valueType\": \"DateTime\"\n"
//            + "            }\n"
//            + "        }\n"
//            + "        },\n"
//            + "        \"vehicleType\": {\n"
//            + "        \"type\": \"Property\",\n"
//            + "        \"description\": \"차량 종류\",\n"
//            + "        \"valueType\": \"Enum\",\n"
//            + "        \"valid\": {\n"
//            + "            \"minLength\": 1,\n"
//            + "            \"maxLength\": 256\n"
//            + "        },\n"
//            + "        \"enum\": [\n"
//            + "            \"bus\",\n"
//            + "            \"truck\",\n"
//            + "            \"bike\",\n"
//            + "            \"sedan\"\n"
//            + "        ]\n"
//            + "        },\n"
//            + "        \"speed\": {\n"
//            + "        \"type\": \"Property\",\n"
//            + "        \"description\": \"차량 속도\",\n"
//            + "        \"valueType\": \"Double\",\n"
//            + "        \"valid\": {\n"
//            + "            \"minimum\": 0\n"
//            + "        },\n"
//            + "        \"childAttributes\": {\n"
//            + "            \"unitCode\": {\n"
//            + "            \"valueType\": \"Enum\",\n"
//            + "            \"enum\": [\n"
//            + "                \"km/h\",\n"
//            + "                \"mph\"\n"
//            + "            ]\n"
//            + "            },\n"
//            + "            \"observedAt\": {\n"
//            + "            \"valueType\": \"DateTime\"\n"
//            + "            }\n"
//            + "        }\n"
//            + "        }\n"
//            + "    },\n"
//            + "    \"required\": [\n"
//            + "        \"speed\",\n"
//            + "        \"location\"\n"
//            + "    ],\n"
//            + "    \"reference\": [\n"
//            + "        \"https://geojson.org/schema/Geometry.json\"\n"
//            + "    ],\n"
//            + "    \"@context\": \"http://172.16.28.35:3005/e8ight-context.jsonld\"\n"
//            + "    }";
//
//
//
//}
